# Store Type creation script using Invoke-RestMethod
# Generated by Doctool

# Configuration - set these variables before running
$KeyfactorHostname = $env:KEYFACTOR_HOSTNAME
$KeyfactorApiPath = if ($env:KEYFACTOR_API_PATH) { $env:KEYFACTOR_API_PATH } else { "KeyfactorAPI" }
$KeyfactorAuthToken = $env:KEYFACTOR_AUTH_TOKEN

$Headers = @{
    "Authorization" = "Bearer $KeyfactorAuthToken"
    "Content-Type" = "application/json"
    "x-keyfactor-requested-with" = "APIClient"
}

Write-Host "Creating store type: AEMCM"
$Body = @'
{
  "Name": "Adobe Experience Manager Cloud Manager",
  "ShortName": "AEMCM",
  "Capability": "AEMCM",
  "ServerRequired": true,
  "BlueprintAllowed": false,
  "PowerShell": false,
  "LocalStore": false,
  "PrivateKeyAllowed": "Required",
  "CustomAliasAllowed": "Required",
  "StorePathType": "",
  "StorePathValue": "",
  "SupportedOperations": {
    "Add": true,
    "Remove": true,
    "Discovery": true,
    "Enrollment": false
  },
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "Properties": [
    {
      "Name": "ImsOrgId",
      "DisplayName": "IMS Organization ID",
      "Description": "The Adobe IMS Organization ID (e.g. 'XXXXXXXX@AdobeOrg'), sent as the 'x-gw-ims-org-id' header on Cloud Manager API requests. This is an identifier, not a credential.",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": false
    },
    {
      "Name": "ImsTokenUrl",
      "DisplayName": "IMS Token Endpoint",
      "Description": "The Adobe IMS OAuth Server-to-Server token endpoint used to obtain access tokens.",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "https://ims-na1.adobelogin.com/ims/token/v3",
      "Required": true,
      "IsPAMEligible": false
    },
    {
      "Name": "ImsScopes",
      "DisplayName": "IMS Scopes",
      "Description": "Comma-separated IMS scopes requested for the access token.",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "openid,AdobeID,read_organizations,additional_info.projectedProductContext",
      "Required": true,
      "IsPAMEligible": false
    }
  ],
  "EntryParameters": [],
  "JobProperties": []
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

